# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="powerline"

POWERLINE_RIGHT_A="mixed"
POWERLINE_HIDE_HOST_NAME="true"
POWERLINE_FULL_CURRENT_PATH="true"
POWERLINE_DETECT_SSH="true"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp 
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
# HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse node npm rsync tmux )
plugins=(git battery brew bower encode64 extract forklift gem gpg-agent jira history mvn node npm osx rsync sublime sudo svn z xcode)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:$PATH"
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

# export MANPATH="/usr/local/man:$MANPATH"


# # Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

JIRA_RAPID_BOARD="true"
JIRA_URL=https://jira.thepeaklab.biz

alias heidisql="cd ~/.wine/drive_c/Program\ Files/HeidiSQL/ && wine heidisql.exe"
alias k9j="killall -9 java"

# thanks bitboxer @bitboxer and @klaustopher
# Trees should have colors
alias tree="tree -C"

# Respect ANSI Color Strings
alias less="less -R"

# And now to colourify...

# GRC add color the output (thanks to @klaustopher)
export GRC=`which grc`

alias colourify="$GRC -es --colour=auto"
alias configure='colourify ./configure'
alias diff='colourify diff'
alias make='colourify make'
alias gcc='colourify gcc'
alias g++='colourify g++'
alias as='colourify as'
alias gas='colourify gas'
alias ld='colourify ld'
alias netstat='colourify netstat'
alias ping='colourify ping'
alias traceroute='colourify /usr/sbin/traceroute'


# some more aliases

alias mp3tag="wine ~/.wine/drive_c/Program\ Files/Mp3tag/Mp3tag.exe"
alias backup="duplicity incremental --exclude-device-files --full-if-older-than=30D --exclude-other-filesystems --asynchronous-upload --no-encryption --exclude '**.vdi' --volsize 200 /Users/gil/ file:///Volumes/gil-ext2-1tb/duplicity-backup-mac-users/"
#alias backup="duplicity incremental --exclude-device-files --full-if-older-than=30D --exclude-other-filesystems --asynchronous-upload --no-encryption --exclude '**.v**d' --volsize 200 /Users/gil/ sftp://gil@10.13.1.166/mnt/320-raid1/duplicity-backup-mac-users/"
alias mkvdts2ac3="mkvdts2ac3 --wd ."
source ~/.profile
alias yta="youtube-dl -x --audio-format best --restrict-filenames -t"
[[ -s `brew --prefix`/etc/autojump.sh ]] && . `brew --prefix`/etc/autojump.sh
PATH=$PATH:$HOME/.rvm/bin:$HOME/.cabal/bin:$(brew --prefix ruby)/bin
alias cask-upgrade=" ~/Dropbox/Apps/cask-upgrade.sh "

export JAVA_HOME=`/usr/libexec/java_home`
export SSL_CERT_FILE=/usr/local/opt/curl-ca-bundle/share/ca-bundle.crt


archey
