# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Faster prompt for demos and workshops
command_timeout = 500

[directory]
truncation_length = 2
truncate_to_repo = false

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[nodejs]
symbol = "⬢ "
style = "bold green"

[python]
symbol = "🐍 "
style = "bold yellow"

[golang]
symbol = "🐹 "
style = "bold cyan"

[rust]
symbol = "🦀 "
style = "bold red"

[ruby]
symbol = "🔺 "
style = "bold magenta"

[docker_context]
symbol = "🐳 "
style = "bold blue"

[kubernetes]
disabled = false
