#!/usr/bin/env ruby
# frozen_string_literal: true

require 'shellwords'
require 'fileutils'

if ARGV.size.zero? || ['--help', '-h'].include?(ARGV[0])
  puts <<~HELP
    Usage: audio_waveform [OPTIONS] [AUDIO_FILE]

    Generates a waveform from an audio_wave and saves it as png.

    Idea and ffmpeg taken from:
      https://medium.com/@jud.dagnall/dynamic-range-compression-for-audio-with-ffmpeg-and-compand-621fe2b1a892

      Options:
      --help, -h  Prints this help.
  HELP

  ARGV.size.zero? ? abort : exit
end

file_name = ARGV[0]
raise 'File does not exist!' unless File.exist?(file_name)
raise "Can't read given file" unless File.readable?(file_name)

out = "#{file_name}.png"

system "ffmpeg -i \
       #{Shellwords.escape file_name} \
       -filter_complex 'aformat=channel_layouts=mono,showwavespic=s=1000x200' -frames:v 1 \
       #{Shellwords.escape out}"
