#!/bin/sh

set -eux

yt-dlp -o "%(title)s.%(ext)s" \
       --exec "$HOME/.scripts/leech-audio-convert {}" \
       --audio-format best \
       --audio-quality 0 \
       -x \
       --add-metadata \
       --ignore-errors \
       "$1"
