#!/bin/bash
set -euo pipefail

if [ "$(pgrep Music | wc -l)" -gt 0 ]; then
  artist=$(osascript -e 'tell application "Music" to artist of current track as string');
  title=$(osascript -e 'tell application "Music" to name of current track as string');

  echo "$artist － $title"
else
 echo "Music isn't running"
fi
