#!/bin/bash
set -e

if command_exists caddy; then
  if [ -f "./Caddyfile" ]; then
    caddy run --watch
  else
    port="${1:-8080}"
    caddy file-server --root . --listen "127.0.0.1:$port"
  fi
else
  port="${1:-8080}"
  ruby -run -e httpd . -p "$port"
fi
