#!/bin/bash
set -e

function command_exists {
  type "$1" >/dev/null 2>&1;
}

if command_exists caddy; then
  if [ -f "./Caddyfile" ]; then
    caddy run --watch
  else
    port="${PORT:-8080}"
    caddy file-server -browse --root . --listen "127.0.0.1:$port"
  fi
else
  port="${$PORT:-8080}"
  ruby -run -e httpd . -p "$port"
fi
