#!/usr/bin/ruby --disable-gems
# frozen_string_literal: true

# require_relative follows the rcm ~/.scripts/skill symlink. Do not locate
# cli.rb via dirname of $0.
require_relative "../skill/src/cli"

Skill::CLI.run(ARGV)
