#!/usr/bin/env bash
set -euxo pipefail

filename=$(basename -- "$1")
extension="${filename##*.}"{1##*.*}
gifname="$(basename -s "$extension" "$filename").gif"

ffmpeg -i "$1" \
  -vf "fps=10,scale=320:-1:flags=lanczos" \
  -c:v pam \
  -f image2pipe - | \
    convert -delay 10 \
      - \
      -loop 0 \
      -layers optimize \
      "$gifname"
