name: ShellCheck

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run ShellCheck on scripts
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./scripts"
      - name: Run ShellCheck on skills
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./skills"
